import fs from "fs";
import path from "path";
import { configSchema, type FeedsiloConfig, type DatabaseType } from "./schema";

const PROJECT_ROOT = process.cwd();
const DEFAULT_CONFIG_PATH = path.join(PROJECT_ROOT, "feedsilo.config.json");
const DEFAULT_ENV_PATH = path.join(PROJECT_ROOT, ".env.local");

export function readConfig(
  configPath: string = DEFAULT_CONFIG_PATH
): FeedsiloConfig | null {
  try {
    if (!fs.existsSync(configPath)) return null;
    const raw = fs.readFileSync(configPath, "utf-8");
    const parsed = JSON.parse(raw);
    const result = configSchema.safeParse(parsed);
    return result.success ? result.data : null;
  } catch {
    return null;
  }
}

export function writeConfig(
  config: FeedsiloConfig,
  configPath: string = DEFAULT_CONFIG_PATH,
  envPath: string = DEFAULT_ENV_PATH
): void {
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n", "utf-8");

  const lines: string[] = [
    "# Generated by FeedSilo onboarding — do not edit manually",
    `DATABASE_URL=${config.database.url}`,
    `DATABASE_TYPE=${config.database.type}`,
  ];
  if (config.embeddings?.apiKey) {
    lines.push(`GEMINI_API_KEY=${config.embeddings.apiKey}`);
  }
  if (config.extension?.pairingToken) {
    lines.push(`CAPTURE_SECRET=${config.extension.pairingToken}`);
  }
  if (config.search) {
    lines.push(`SEARCH_KEYWORD_WEIGHT=${config.search.keywordWeight}`);
    lines.push(`SEARCH_VECTOR_WEIGHT=${config.search.semanticWeight}`);
  }
  fs.writeFileSync(envPath, lines.join("\n") + "\n", "utf-8");
}

export function resolveConfig(
  fileConfig: FeedsiloConfig | null
): FeedsiloConfig | null {
  if (!fileConfig) {
    const dbUrl = process.env.DATABASE_URL;
    const dbType = process.env.DATABASE_TYPE as DatabaseType | undefined;
    if (dbUrl && dbType) {
      return configSchema.parse({
        database: { type: dbType, url: dbUrl },
        embeddings: {
          provider: "gemini",
          apiKey: process.env.GEMINI_API_KEY || undefined,
        },
        extension: {
          pairingToken: process.env.CAPTURE_SECRET || undefined,
        },
        search: {
          keywordWeight: process.env.SEARCH_KEYWORD_WEIGHT
            ? parseFloat(process.env.SEARCH_KEYWORD_WEIGHT)
            : 0.4,
          semanticWeight: process.env.SEARCH_VECTOR_WEIGHT
            ? parseFloat(process.env.SEARCH_VECTOR_WEIGHT)
            : 0.6,
        },
      });
    }
    return null;
  }

  return {
    ...fileConfig,
    database: {
      type: (process.env.DATABASE_TYPE as DatabaseType) || fileConfig.database.type,
      url: process.env.DATABASE_URL || fileConfig.database.url,
    },
    embeddings: {
      ...fileConfig.embeddings,
      apiKey: process.env.GEMINI_API_KEY || fileConfig.embeddings?.apiKey,
    },
    extension: {
      ...fileConfig.extension,
      pairingToken:
        process.env.CAPTURE_SECRET || fileConfig.extension?.pairingToken,
    },
    search: {
      keywordWeight: process.env.SEARCH_KEYWORD_WEIGHT
        ? parseFloat(process.env.SEARCH_KEYWORD_WEIGHT)
        : fileConfig.search.keywordWeight,
      semanticWeight: process.env.SEARCH_VECTOR_WEIGHT
        ? parseFloat(process.env.SEARCH_VECTOR_WEIGHT)
        : fileConfig.search.semanticWeight,
    },
  };
}

export function isConfigured(config: FeedsiloConfig | null): boolean {
  return config !== null && !!config.database.type && !!config.database.url;
}

let _resolvedConfig: FeedsiloConfig | null | undefined;

export function getConfig(): FeedsiloConfig | null {
  if (_resolvedConfig !== undefined) return _resolvedConfig;
  const fileConfig = readConfig();
  _resolvedConfig = resolveConfig(fileConfig);
  return _resolvedConfig;
}

export function invalidateConfigCache(): void {
  _resolvedConfig = undefined;
}

export { configSchema, type FeedsiloConfig, type DatabaseType } from "./schema";
