import fs from "fs";
import fsp from "fs/promises";
import path from "path";
import { randomBytes } from "crypto";
import { configSchema, type ScrollbackConfig, type DatabaseType } from "./schema";

const PROJECT_ROOT = /* turbopackIgnore: true */ process.cwd();
const DEFAULT_CONFIG_PATH = path.join(PROJECT_ROOT, "scrollback.config.json");
const DEFAULT_ENV_PATH = path.join(PROJECT_ROOT, ".env.local");

function resolveConfigPath(configPath: string): string {
  return configPath;
}

export function readConfig(
  configPath: string = DEFAULT_CONFIG_PATH
): ScrollbackConfig | null {
  try {
    configPath = resolveConfigPath(configPath);
    if (!fs.existsSync(configPath)) return null;
    const raw = fs.readFileSync(configPath, "utf-8");
    const parsed = JSON.parse(raw);
    const result = configSchema.safeParse(parsed);
    return result.success ? result.data : null;
  } catch {
    return null;
  }
}

export async function readConfigAsync(
  configPath: string = DEFAULT_CONFIG_PATH
): Promise<ScrollbackConfig | null> {
  try {
    configPath = resolveConfigPath(configPath);
    const raw = await fsp.readFile(configPath, "utf-8");
    const parsed = JSON.parse(raw);
    const result = configSchema.safeParse(parsed);
    return result.success ? result.data : null;
  } catch {
    return null;
  }
}

// Keys that writeConfig manages — everything else is preserved as-is
const MANAGED_ENV_KEYS = new Set([
  "DATABASE_URL",
  "DATABASE_TYPE",
  "EMBEDDINGS_PROVIDER",
  "GEMINI_API_KEY",
  "OPENAI_API_KEY",
  "CAPTURE_SECRET",
  "SEARCH_KEYWORD_WEIGHT",
  "SEARCH_VECTOR_WEIGHT",
]);

function getEnvApiKey(provider: ScrollbackConfig["embeddings"]["provider"]): string | undefined {
  return provider === "openai"
    ? process.env.OPENAI_API_KEY || undefined
    : process.env.GEMINI_API_KEY || undefined;
}

function getEnvProvider(fallback: ScrollbackConfig["embeddings"]["provider"]): ScrollbackConfig["embeddings"]["provider"] {
  const provider = process.env.EMBEDDINGS_PROVIDER || process.env.AI_PROVIDER;
  return provider === "openai" || provider === "gemini" ? provider : fallback;
}

export function writeConfig(
  config: ScrollbackConfig,
  configPath: string = DEFAULT_CONFIG_PATH,
  envPath: string = DEFAULT_ENV_PATH
): void {
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n", "utf-8");

  // Read existing .env.local and preserve unmanaged vars (R2, XAPI, etc.)
  const preserved: string[] = [];
  let authSecretLine: string | null = null;
  if (fs.existsSync(envPath)) {
    const existing = fs.readFileSync(envPath, "utf-8");
    for (const line of existing.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx);
      if (key === "AUTH_SECRET") {
        authSecretLine = line;
        continue;
      }
      if (!MANAGED_ENV_KEYS.has(key)) {
        preserved.push(line);
      }
    }
  }

  const lines: string[] = [
    "# Generated by Scrollback — managed vars below, user vars preserved at end",
    `DATABASE_URL=${config.database.url}`,
    `DATABASE_TYPE=${config.database.type}`,
  ];
  if (config.embeddings?.provider === "openai" && config.embeddings?.apiKey) {
    lines.push(`OPENAI_API_KEY=${config.embeddings.apiKey}`);
  } else if (config.embeddings?.provider === "gemini" && config.embeddings?.apiKey) {
    lines.push(`GEMINI_API_KEY=${config.embeddings.apiKey}`);
  }
  if (config.extension?.pairingToken) {
    lines.push(`CAPTURE_SECRET=${config.extension.pairingToken}`);
  }
  if (config.search) {
    lines.push(`SEARCH_KEYWORD_WEIGHT=${config.search.keywordWeight}`);
    lines.push(`SEARCH_VECTOR_WEIGHT=${config.search.semanticWeight}`);
  }

  if (!authSecretLine && process.env.AUTH_SECRET) {
    authSecretLine = `AUTH_SECRET=${process.env.AUTH_SECRET}`;
  }
  if (!authSecretLine) {
    authSecretLine = `AUTH_SECRET=${randomBytes(32).toString("hex")}`;
  }
  lines.push(authSecretLine);

  if (preserved.length > 0) {
    lines.push("");
    lines.push("# User-managed vars (preserved across config writes)");
    lines.push(...preserved);
  }

  fs.writeFileSync(envPath, lines.join("\n") + "\n", "utf-8");
}

export function resolveConfig(
  fileConfig: ScrollbackConfig | null
): ScrollbackConfig | null {
  if (!fileConfig) {
    const dbUrl = process.env.DATABASE_URL;
    const dbType = process.env.DATABASE_TYPE as DatabaseType | undefined;
    if (dbUrl && dbType) {
      const provider = getEnvProvider(process.env.OPENAI_API_KEY ? "openai" : "gemini");
      return configSchema.parse({
        database: { type: dbType, url: dbUrl },
        embeddings: {
          provider,
          apiKey: getEnvApiKey(provider),
        },
        extension: {
          pairingToken: process.env.CAPTURE_SECRET || undefined,
        },
        search: {
          keywordWeight: process.env.SEARCH_KEYWORD_WEIGHT
            ? parseFloat(process.env.SEARCH_KEYWORD_WEIGHT)
            : 0.4,
          semanticWeight: process.env.SEARCH_VECTOR_WEIGHT
            ? parseFloat(process.env.SEARCH_VECTOR_WEIGHT)
            : 0.6,
        },
      });
    }
    return null;
  }

  const embeddingsProvider = getEnvProvider(fileConfig.embeddings.provider);

  return {
    ...fileConfig,
    database: {
      type: (process.env.DATABASE_TYPE as DatabaseType) || fileConfig.database.type,
      url: process.env.DATABASE_URL || fileConfig.database.url,
    },
    embeddings: {
      ...fileConfig.embeddings,
      provider: embeddingsProvider,
      apiKey:
        getEnvApiKey(embeddingsProvider) ||
        fileConfig.embeddings?.apiKey,
    },
    extension: {
      ...fileConfig.extension,
      pairingToken:
        process.env.CAPTURE_SECRET || fileConfig.extension?.pairingToken,
    },
    search: {
      keywordWeight: process.env.SEARCH_KEYWORD_WEIGHT
        ? parseFloat(process.env.SEARCH_KEYWORD_WEIGHT)
        : fileConfig.search.keywordWeight,
      semanticWeight: process.env.SEARCH_VECTOR_WEIGHT
        ? parseFloat(process.env.SEARCH_VECTOR_WEIGHT)
        : fileConfig.search.semanticWeight,
    },
  };
}

export function isConfigured(config: ScrollbackConfig | null): boolean {
  return config !== null && !!config.database.type && !!config.database.url;
}

let _resolvedConfig: ScrollbackConfig | null | undefined;
let _resolvedConfigPromise: Promise<ScrollbackConfig | null> | undefined;

/** Synchronous getter — uses cached value or falls back to sync file read */
export function getConfig(): ScrollbackConfig | null {
  if (_resolvedConfig !== undefined) return _resolvedConfig;
  const fileConfig = readConfig();
  _resolvedConfig = resolveConfig(fileConfig);
  return _resolvedConfig;
}

/** Async getter — non-blocking file read, populates the same cache */
export async function getConfigAsync(): Promise<ScrollbackConfig | null> {
  if (_resolvedConfig !== undefined) return _resolvedConfig;
  if (_resolvedConfigPromise) return _resolvedConfigPromise;
  _resolvedConfigPromise = readConfigAsync().then((fileConfig) => {
    _resolvedConfig = resolveConfig(fileConfig);
    _resolvedConfigPromise = undefined;
    return _resolvedConfig;
  });
  return _resolvedConfigPromise;
}

export function invalidateConfigCache(): void {
  _resolvedConfig = undefined;
  _resolvedConfigPromise = undefined;
}

export { configSchema, type ScrollbackConfig, type DatabaseType, type AiProvider } from "./schema";
